### PR TITLE
User friendly random number generator

### PR DESCRIPTION
**Pull request by masrourmouad**
Math.random(12) output a number between 0 and 12

### CODE REVIEW

**Comment by masrourmouad** [comment]
ok , working on it

**Comment by masrourmouad** [comment]
Changes are made

**Comment by marcobambini** [comment]
Thanks @masrourmouad, @hallzy is right, documentation needs to be updated to reflect the change.
Even if I am not sure about the value that your changes add.
What other people think?

**Comment by masrourmouad** [comment]
Thanks @marcobambini for you comment, on my side I intend to render the function math.random
able to detect if the input is an integer or  a float and generate a number between 0 and input

**Comment by marcobambini** [comment]
If we change the Math.rand method then, to be really useful, I think it should work in the following way:

- if no parameters are passed then the output will be a number between 0 and 1 (like the current version)
- if one parameter is passed it must be Int or Float and a number between 0 and the parameter will be returned
- if two parameters are passed they must be both Int or Float and a number between parameter1 and parameter2 will be returned
- any other parameter will be ignored

What do you think?

**Comment by masrourmouad** [comment]
Nice idea

**Comment by marcobambini** [comment]
It turns out that the problem is much more complicated and that rand() is a terrible API.
We need a much better multiplatform function (to support crypto and games) but unfortunately arc4random is not available on all platforms.

**Comment by masrourmouad** [comment]
true, Wren have a good API , we need  a seed method .

**Comment by marcobambini** [comment]
Fixed by 
https://github.com/marcobambini/gravity/commit/855d44a244ce8cf564d7609b34ee3ceb758e984a

**Pull request closed without merging**
