### PR TITLE
Added ternary expr and switch stmt codegen

### PR DESCRIPTION
**Pull request by asp100m**
This makes ternary operator and switch statement work.

### CODE REVIEW

**Comment by marcobambini** [comment]
@asp100m this is really awesome, I truly appreciate your help.

**Comment by marcobambini** [comment]
@asp100m I found on GitLab that you fixed a lot of issues: https://gitlab.com/asp100m/Gravity/-/commits/jim
It is an excellent work, is there any chance that you merge your fixes into this official repo?
Are you actively using Gravity or you fixed it just for fun?

Thanks a lot again for your help.

**Comment by asp100m** [comment]
@marcobambini Mostly fixes in my repo are temporary workarounds and let me code like those languages I familiar. So I don't think that's a good idea to merge them into official repo. They may break the design of Gravity. But, you can use them anyway if you want.

I was trying to replace QuakeC with Gravity for myself. Therefore, it's just for fun.

**Comment by marcobambini** [comment]
@asp100m I see, thanks.
It seems to me that you found a lot of issues related to Gravity so I think it is a good idea to take a look at them.

**Pull request merged**
