### PR TITLE
Added a random() method for System

### PR DESCRIPTION
**Pull request by hallzy**
```swift
System.random(-5, 10) // returns a random integer between -5 and 10 inclusively
```

### CODE REVIEW

**Comment by marcobambini** [comment]
Thanks @hallzy. As soon as  I'll finalize the opt subsystem we'll move the rand method to the more appropriate Math class.

**Comment by hallzy** [comment]
Okay sounds good. I wasn't sure if it would be better suited in a math class or a system. Javascript seems to have it as part of their math class, but C seems to just include it in stdlib rather than their math header for instance.

Math seems like a descent place to put it though

**Comment by hallzy** [comment]
I was not aware of this. I have always done it that way. How would you generate a random number in C?

**Comment by kazzkiq** [comment]
Cool method, but wouldn't this make more sense inside a math-related class?

Example:

```js
// All mathematical methods goes inside this "Math" class
Math.random(-5, 10);
```

**Comment by hallzy** [comment]
@marcobambini mentioned this earlier in this PR. I think it could probably work in either, but Math certainly makes sense, and I would not object to this change.

I believe he is going to merge it into a Math class once he finalizes the opt subsystem (basically, he is adding a way for us to more easily add new classes in a file separate from the gravity_core... so once he has done that we will be moving it)

**Comment by kazzkiq** [comment]
@hallzy Oh, sorry, completely missed that comment. 😄

**Comment by hallzy** [comment]
np :)

**Comment by marcobambini** [comment]
@hallzy instead of the old and insure stand/rand functions we should use arc4random (available in stdlib.h). This can helps http://stackoverflow.com/questions/3420581/how-to-select-range-of-values-when-using-arc4random

**Comment by hallzy** [comment]
I am unable to get it to work. It doesn't seem to be in stdlib. I get a compilation warning for an implicit declaration, and a compilation error for the unittest target.

When I look up anything about it I get more stuff related to Swift and Obj-C than actual C.

**Comment by brandon-ray** [comment]
Should this function be named differently to show it only handles integers? Something like ```randomInt``` or similar. Then we can have other random value functions like ```randomFloat`` and then the "regular" random function ```random``` could return a value between 0 and 1 like other languages.

It would seem odd to me to only support random integers.

**Comment by marcobambini** [comment]
Good point @brandon-ray and based on your observation I'd suggest to move the random method from System meta to Int meta class so user will be able to write:
Int.random(...)

**Comment by brandon-ray** [comment]
Ah that is an even better idea, then we can have ```Float.random(...)```, ```Bool.random()```, etc.

**Comment by hallzy** [comment]
I like that idea better than just a general system or math method.

If someone else wants to make the change, go ahead... I don't think I am going to have much free time for at least the next few days

**Pull request merged**
