### PR TITLE
Updated math doc after the new math functions were merged

### PR DESCRIPTION
**Pull request by hallzy**
This is the updated math docs after my additions to the math class were just merged.

### CODE REVIEW

**Comment by marcobambini** [comment]
Not sure about the conflict to be resolved.
Any hint?

**Comment by hallzy** [comment]
I'll have a look tonight when I have a computer I can sit at.

**Comment by hallzy** [comment]
actually just looked at it but I can't really fix it here. Keep both of the lines if you want to do it, otherwise I will do it tonight.

**Comment by hallzy** [comment]
Not sure what happened but it looks like some stuff wasn't merged, such as the cbrt, log10 and logx stuff. This page says that this has been closed with unmerged commits and based on the states of the files it looks like it the changes that are missing should now just go in.

**Comment by marcobambini** [comment]
@hallzy not sure what happened.
I just kept both the the lines as you suggested.
Can you please take a look at this issue?

**Comment by hallzy** [comment]
Sure not a problem. I will do it in the morning or afternoon though as it's 2:30am here.

**Comment by hallzy** [comment]
Actually it looks like it can be merged the way it is now.

**Comment by marcobambini** [comment]
Thanks a lot, I really appreciate.

**Pull request merged**
