### PR TITLE
Remove trailing whitespace in many files.

### PR DESCRIPTION
**Pull request by neysofu**
As common knowledge has it, trailing whitespace is bad. It creates commit noise, it is inconsistent, and makes editing files harder with editors that rely on hotkeys and keyboard commands.

I have deleted trailing whitespace in many files. I made sure to do so only when it made sense to me and when I was sure it wouldn't break anything.

### CODE REVIEW

**Comment by marcobambini** [comment]
@neysofu can you please update your PR to have no conflicts with the latest version?
Thanks.

**Comment by neysofu** [comment]
Working on it right now. It will be ready in a few hours.

**Comment by neysofu** [comment]
Ready to merge.

**Comment by marcobambini** [comment]
Thanks @neysofu!

**Pull request merged**
