### PR TITLE
Added a String.substr() method

### PR DESCRIPTION
**Pull request by hallzy**
added a substring method that takes either 1 or 2 arguments.

if one argument is provided, it takes the substring defined by that index of the string, to the end of the string, otherwise it is the string defined by two given indices.

For example:

```swift
var str = "Hello, World!"
return str.substr(7, 11) // "World"... or str.substr(7, -2)
```

Not sure if someone else has a better name for it, but I am open to suggestions if substr() is not appealing.

It also seems that some languages specify the ending index of the character after the last character you want, while this stops the substring at the character you specify...

For instance, in JS that substring command I gave above would return "Worl" instead of "World".

I have also seen some languages take the substring length as the second argument and that is a possibility as well, instead of what this implementation gives.

Perhaps this needs further discussion on if the name needs to be changed, or we want to change the meaning of the 2nd index

### CODE REVIEW

**Comment by marcobambini** [comment]
I'd suggest to just extends the string_loadat implementation (it now accepts an integer index only) with range support. In this way you can use a syntax like:
`string[1...3]`
to get a substring based on a range index.

Take a look at https://github.com/munificent/wren/blob/master/test/core/string/subscript_range.wren for some examples.

**Comment by hallzy** [comment]
That's a good idea... I will have a look later on

**Comment by hallzy** [comment]
Okay, I have modified the string loadat to handle ranges...

I also did what wren did, and if the range is in reverse order, it returns a reversed string as well. And negative indices still work.

**Comment by marcobambini** [comment]
Very well done @hallzy I really appreciate your help!

**Comment by marcobambini** [comment]
I wondering if the three costly **strlen(original)** can be replaced by **string->len**.

**Comment by hallzy** [comment]
It could be replaced with `string->len` for sure. Or `uint32_t original_len = string->len` and use `original_len` instead.

**Pull request merged**
