### PR TITLE
Fixes for visual studio

### PR DESCRIPTION
**Pull request by cartman300**

### CODE REVIEW

**Comment by marcobambini** [comment]
Very well done, thanks a lot!

**Comment by marcobambini** [comment]
@cartman300 it would be really useful to have also a VS project to add to the repository (like the Xcode one).

**Comment by WorksOfBarry** [comment]
@marcobambini The code to remove the cast actually fixes some of the problems on IBM i as well. Thank you @cartman300

**Comment by cartman300** [comment]
@marcobambini i have a VS solution in my repo, with a few additional files and some configuration it can be set up to compile the project as-is without any changes to a dll and exporting all the symbols. I'll see what i can do later today to clean it up a bit.

**Comment by marcobambini** [comment]
@cartman300 thank you very much!

**Pull request merged**
